Created basic routing for signing up, logging in and logging out a user.
Code-the-Dream-School/bb-practicum-team-3-back pull request #1
Opened 2023-03-25 00:35 UTC by mariolarios

I added the basic routes for registering a new user, signing a user up and logging the user off. I also tested the features using postman and the test user was added to mongo db.

2023-03-27 14:10 UTC, alton-michaux requested changes
Hey @mariolarios this is good work here, just a couple of things:

I'm unable to spin up the server for some reason. Not sure, but it seems to be complaining about a mal-formatted string(?)

![image](https://user-images.githubusercontent.com/73147385/227963141-2c6605d1-fafd-413e-a8b3-e631edcc72d8.png)

Also, it's usually a good idea to split up big PRs like this, but since these are the early stages of the app building process it's ok to have these massive changes being introduced. If you'll notice, this PR only has 1 commit.

The key is to commit early and often: that way, you as a developer don't have to undo all your changes if something goes wrong, reviewers can see a clear timeline of what you did and in what order you did them, etc. You don't have to worry about it for this PR, but it's good to keep in mind for the future.

The only blocker for me is getting the server to start (I used `npm run dev` after installing dependencies).

As soon as I can get that up and running I'll approve, nice job man 💪🏾

2023-03-27 14:10 UTC, alton-michaux commented on src/app.js
> +    console.log(error);
We probably want to do something like `throw new Error...` instead of just `console.log` here. Not a huge deal at all for this, but most codebases prefer to remove any `console.log` or debugging statements before hitting production.

### UPDATE:
- It seems like our server issue is stemming from a couple of places in the is file:
    - line 1: we should remove `{ path: "src/.env" }` altogether and leave it as `require("dotenv").config();` since our `.env` should be in our directory `root` folder
    - line 38: we should change  `process.env.MONGO_URL` to `process.env.MONGO_URI` to match our `.env` file

After making these changes, the server ran for me.

2023-03-27 14:10 UTC, alton-michaux commented on src/controllers/auth.js
> +    throw new CustomError.BadRequestError("Email already exists");
Nice use of error handling here.

2023-03-27 14:10 UTC, alton-michaux commented on src/errors/index.js
> +};
Nice job with the custom error handling here

2023-03-27 14:10 UTC, alton-michaux commented on src/models/User.js
> +    }
Just curious, does `bcrypt` provide the `JWT tokens` or are those two different packages that work together?

2023-03-27 14:10 UTC, alton-michaux commented on src/utils/checkPermissions.js
> +module.exports = checkPermissions;
Good job with all the attention being paid to user authentication, very important

2023-03-27 14:10 UTC, alton-michaux commented on src/utils/jwt.js
> +const jwt = require("jsonwebtoken");
Ok, this answers my question from before. Gotcha, again nice job.

2023-03-27 18:08 UTC, madebymiguel requested changes
Overall looks good to me. Just those small changes. One more thing is that you should add a `.env.example` file with the variable names. Ex: `MONGO_URI=` that way the rest of the group can fill those values in to run locally.

2023-03-27 18:08 UTC, madebymiguel commented on src/utils/createTokenUser.js
> +  return { name: user.name, userId: user._id, role: user.role };
`role: user.role` is not required for this project

2023-03-27 18:08 UTC, madebymiguel commented on src/app.js
> +    app.listen(port, console.log(`Server is listening on port ${port}...`));
I would personally write `console.log(`Server is running at http://localhost:${port}`)`. For quick access to the server for the terminal.

2023-03-27 18:08 UTC, madebymiguel commented on src/controllers/auth.js
> +  res.cookie("token", "logout", {
Would change `"token"` to ``${process.env.COOKIE_NAME}`` and add the token name in `.env`

2023-03-27 18:08 UTC, madebymiguel commented on src/utils/checkPermissions.js
> +  if (requestUser.role === "admin") return;
This admin check is not required.

2023-03-27 18:08 UTC, madebymiguel commented on src/utils/jwt.js
> +  res.cookie("token", token, {
Same thing here ``${process.env.COOKIE_NAME}``

2023-03-28 00:25 UTC, frankstepanski commented
Yes, good code overall. After you make the small changes outlined by @madebymiguel and @alton-michaux you should be good to go. As far as committing, anytime you create a new file should have a commit, and any change beyond creating a few functions should be a commit.

2023-03-28 00:42 UTC, frankstepanski reviewed
Yes, good code overall. After you make the small changes outlined by @madebymiguel and @alton-michaux you should be good to go. As far as committing, anytime you create a new file should have a commit, and any change beyond creating a few functions should be a commit.

2023-03-29 23:33 UTC, madebymiguel approved these changes

2023-03-30 13:25 UTC, alton-michaux approved these changes
Nice job, changes made and code looks good. Approved ✅

2023-03-30 13:32 UTC, merged